const express = require("express");
const router = express.Router();

const authRoutes = require("./auth/auth");
const googleAuthRoutes = require("./googleAuth/googleAuth");
const passwordRoutes = require("./password/password");
const userRoutes = require("./user/user");
const doctorRoutes = require("./doctor/doctor");
const hospitalRoutes = require("./hospital/hospital");
const daycareRoutes = require("./daycare/daycare");
const caretakerRoutes = require("./caretaker/caretaker");
const shopRoutes = require("./shop/shop");
const ngoRoutes = require("./ngo/ngo");
const petsRoutes = require("./pets/pets");
const productsRoutes = require("./products/products");
const servicesRoutes = require("./services/services");
const appointmentsRoutes = require("./appointments/appointments");
const ordersRoutes = require("./orders/orders");
const userPetRoutes = require("./userPet/userPet");
const adminRoutes = require("./admin/admin");
const enquiryRoutes = require("./enquiry/enquiry");
const analyticsRoutes = require("./analytics/analytics");
const cartRoutes = require("./cart/cart");
const paymentRoutes = require("./payment/payment");
const whatsappRoutes = require("./whatsapp/whatsapp");
const platformFeeRoutes = require("./platformFee/platformFee");
const coinsRoutes = require("./coins/coins");
const walletRoutes = require("./wallet/wallet");
const newsletterRoutes = require("./newsletter/newsletter");

router.use("/auth", authRoutes);
router.use("/auth", googleAuthRoutes);
router.use("/auth", passwordRoutes);
router.use("/user", userRoutes);
router.use("/doctor", doctorRoutes);
router.use("/hospital", hospitalRoutes);
router.use("/daycare", daycareRoutes);
router.use("/caretaker", caretakerRoutes);
router.use("/shop", shopRoutes);
router.use("/ngo", ngoRoutes);
router.use("/pets", petsRoutes);
router.use("/products", productsRoutes);
router.use("/services", servicesRoutes);
router.use("/appointments", appointmentsRoutes);
router.use("/orders", ordersRoutes);
router.use("/user-pets", userPetRoutes);
router.use("/admin", adminRoutes);
router.use("/", enquiryRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/cart", cartRoutes);
router.use("/payment", paymentRoutes);
router.use("/platform-fee", platformFeeRoutes);
router.use("/whatsapp", whatsappRoutes);
router.use("/notifications", require("./notifications/notifications"));
router.use("/coins", coinsRoutes);
router.use("/wallet", walletRoutes);
router.use("/newsletter", newsletterRoutes);

module.exports = router;
