const mongoose = require("mongoose");

const notificationSchema = new mongoose.Schema(
  {
    recipient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    sender: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    type: {
      type: String,
      required: true,
      enum: [
        "ACCOUNT_CREATED",
        "ACCOUNT_APPROVED",
        "ACCOUNT_REJECTED",
        "ACCOUNT_SUSPENDED",
        "PASSWORD_CHANGED",
        "NEW_DEVICE_LOGIN",
        "NEW_PROVIDER_SIGNUP",
        "SUSPICIOUS_LOGIN",
        "PAYMENT_SUCCESS",
        "REFUND_ISSUED",
        "PAYMENT_RECEIVED_IN_ESCROW",
        "ESCROW_RELEASED_TO_WALLET",
        "WITHDRAWAL_PROCESSED",
        "WITHDRAWAL_FAILED",
        "HIGH_VALUE_TRANSACTION",
        "ESCROW_RELEASE_ERROR",
        "PAYMENT_GATEWAY_FAILURE",
        "BOOKING_CONFIRMED",
        "BOOKING_CANCELLED_BY_PROVIDER",
        "APPOINTMENT_REMINDER_24H",
        "APPOINTMENT_COMPLETED",
        "PRESCRIPTION_UPLOADED",
        "DISPUTE_UPDATE",
        "NEW_BOOKING_RECEIVED",
        "BOOKING_CANCELLED_BY_USER",
        "UPCOMING_APPOINTMENT_REMINDER",
        "DISPUTE_RAISED",
        "ESCROW_RELEASED",
        "HIGH_DISPUTE_RATE_PROVIDER",
        "FRAUD_COMPLETION_SIGNAL",
        "ORDER_PLACED",
        "ORDER_SHIPPED",
        "ORDER_DELIVERED",
        "NEW_ORDER_RECEIVED",
        "SHIPPING_DEADLINE_NEAR",
        "RETURN_REQUESTED",
        "ORDER_STUCK_STATUS",
        "HIGH_RETURN_RATE_SHOP",
        "BOOKING_ACCEPTED",
        "SERVICE_COMPLETED",
        "NEW_BOOKING_REQUEST",
        "SAFETY_COMPLAINT",
        "REPEATED_NEGATIVE_REPORTS",
        "ADOPTION_REQUEST_SUBMITTED",
        "ADOPTION_APPROVED",
        "ADOPTION_REJECTED",
        "ADOPTION_COMPLETED",
        "NEW_ADOPTION_REQUEST",
        "NEW_RESCUE_REPORT",
        "ADOPTION_DISPUTE",
        "ABUSE_REPORT",
        "DISPUTE_CREATED",
        "ADMIN_DECISION",
        "CASE_CLOSED",
        "NEW_DISPUTE",
        "DISPUTE_PENDING_48H",
        "LEGAL_ESCALATION",
        "VACCINATION_REMINDER",
        "FOLLOWUP_REMINDER",
        "NEW_APPOINTMENT",
        "APPOINTMENT_REQUESTED",
        "APPOINTMENT_UPDATE",
        "NEW_ORDER",
        "ORDER_UPDATE",
        "NEW_REVIEW",
        "NEW_PRODUCT_REVIEW",
        "NEW_ENQUIRY",
        "ROLE_UPDATE",
        "GENERAL",
      ],
    },
    title: {
      type: String,
      required: true,
    },
    message: {
      type: String,
      required: true,
    },
    payload: {
      type: Object, // Flexible for different entity IDs like orderId, appointmentId, etc.
    },
    isRead: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true },
);

// Auto-delete notifications 24 hours after creation.
notificationSchema.index(
  { createdAt: 1 },
  { expireAfterSeconds: 24 * 60 * 60 },
);

module.exports = mongoose.model("Notification", notificationSchema);
